### ISSUE TITLE
Błędne przekierowanie na FB i LinkedIn

### ISSUE THREAD

**Issue by bmankowski** [bmankowski/itconnect-www#1]
Na podstronie "Kontakt" przekierowanie są niepoprawne. Klawisz FB przekierowuje na LI, a klawisz LI przekierowuje na FB

**Comment by pureunderground** [comment]
Gotowe:
http://www.pureunderground-studio.pl/DEMO/itconnect/pl/kontakt

**Comment by bmankowski** [comment]
Działa.
