### ISSUE TITLE
Dłuższe pozostawanie na stronie

### ISSUE THREAD

**Issue by bmankowski** [bmankowski/itconnect-www#10]
Od konsultanta - cytuję:
"Dodatkowo coś, co już męczyło na starej stronie, a tu jest tak samo -> zaczynam dodawać ogłoszenie, dzwoni do mnie np. telefon/ktoś coś ode mnie chce i zajmuję się przez chwilę czymś innym, wracam po chwili do dodawania ogłoszenia, klikam publikuj i wywala mnie ze strony. Musze jeszcze raz się logować i dodawać ogłoszenie od nowa.
Czy można zrobić tak, żeby ten czas zanim wywali mnie ze strony był jednak dłuższy?"

Czyli prośba o przedłużenie czasu sesji do 1 godziny.

**Comment by pureunderground** [comment]
Poprawione - Czas trwania sesji zwiększony do 60 minut.

**Comment by bmankowski** [comment]
Super
