### ISSUE TITLE
Małe okno w które wpisuje się opis stanowiska

### ISSUE THREAD

**Issue by bmankowski** [bmankowski/itconnect-www#11]
Przy dodawaniu stanowiska, wszystko jest w jednym oknie, którego nie można powiększyć (mało przejrzyste, praktycznie nie ma podglądu)

**Comment by pureunderground** [comment]
Gotowe - okno edytora jest już powiększone tak że możemy zobaczyć całość treści.

**Comment by bmankowski** [comment]
ok
