### ISSUE TITLE
Niepotrzebnie dwustopniowe dodawanie ogłoszeń

### ISSUE THREAD

**Issue by bmankowski** [bmankowski/itconnect-www#12]
Nie można dodać od razu oferty – najpierw trzeba dodać stanowisko, które staje się szablonem i dopiero na podstawie tego dodaje się ogłoszenie (dodanie ogłoszenia zajmuje więcej czasu – rzadko dodajemy oferty na identyczne stanowiska)

Czy możemy to uprościć i zrobić po prostu dodawanie ogłoszeń?

**Comment by pureunderground** [comment]
Gotowe

**Comment by bmankowski** [comment]
Jak teraz dodaje się ogłoszenia o prace? Czy to jest jako -> Utwórz artykuł?

**Comment by pureunderground** [comment]
Dokładnie tak, poniżej krótka instrukcja dodawania nowych ofert pracy:
Aby dodać ofertę w panelu administratora wchodzimy w artykuły, następnie w kategorię "Praca" dla ofert po polsku bądź "Jobs" dla ofert w języku angielskim. Klikamy na przycisk "Utwórz", podajemy tytuł (dla czytelności najlepiej według obecnego wzoru czyli np: Programista Java [Warszawa]), z zakładki "Praca" (pod tytułem) wybieramy stanowisko i lokalizacje według których będzie działać wyszukiwanie, następnie w zakładce "Treści" klikamy na ikonkę Templates (pierwsza ikona z prawej w edytorze) aby wkleić wcześniej przygotowaną treść-szablon oferty.
