### ISSUE TITLE
Strefa pracownika formatowanie artykułów

### ISSUE THREAD

**Issue by bmankowski** [bmankowski/itconnect-www#13]
Artykuły proponuję wrzucić w ramki i trochę wyśrodkować, tak jak wyglądają teraz oferty w zakładce „praca”.

**Comment by pureunderground** [comment]
Gotowe, proszę pamiętać że w artykułach możemy ustawić jaka część jest widoczna w wykazie wszystkich artykułów oraz po kliknięciu w "Czytaj więcej"

**Comment by pureunderground** [comment]
Gotowe
