### ISSUE TITLE
Dodanie możliwości przekierowania ze strony mobilnej na stronę podstawową

### ISSUE THREAD

**Issue by bmankowski** [bmankowski/itconnect-www#17]
W wersji mobilnej warto dodać opcję przekierowania na stronę podstawową - niektórzy mają mega duże wyświetlacze i nie chcą korzystać z mobilnych wersji portali

**Comment by pureunderground** [comment]
Gotowe. Witryna stworzona jest w technice RWD, oznacza to że w rozdzielczości większej niż standardowa tabletowa/telefonowa witryna będzie się wyświetlać niezależnie od posiadanego urządzenia i bez niepotrzebnego przełącznika wersji witryny.

**Comment by bmankowski** [comment]
Ok.
