### ISSUE TITLE
Błędne przekierowanie na ofertę dla Klientów zamiast do ofert pracy

### ISSUE THREAD

**Issue by bmankowski** [bmankowski/itconnect-www#2]
Jak wchodzę w: Oferta -> dla szukających pracy

Na samym dole klikam w „szukaj ofert pracy” i przekierowuje do oferty dla klientów zamiast do ofert pracy

**Comment by pureunderground** [comment]
Gotowe:
http://www.pureunderground-studio.pl/DEMO/itconnect/pl/oferta/dla-szukajacych-pracy

**Comment by bmankowski** [comment]
Działa.
