### ISSUE TITLE
Problemy z wersją anglojęzyczną

### ISSUE THREAD

**Issue by bmankowski** [bmankowski/itconnect-www#20]
Zakładka Home - button dla pracodawców przekierowuje do 404, a ten dla szukających pracy na pustą stronę
     - Zakładka Jobs - stanowiska na liście rozwijalnej i oferty pracy są po polsku, podobnie buttony
     - zakładka Offer -> Jobseeker -> buttom "see jobs" przkierowuje do 404 - Category not found
     - zakładka Contact jest cała po polsku

**Comment by pureunderground** [comment]
Gotowe

**Comment by bmankowski** [comment]
Wszystko ok
