### ISSUE TITLE
Szukanie - przesunięcie na wyniki

### ISSUE THREAD

**Issue by bmankowski** [bmankowski/itconnect-www#22]
Po naciśnięciu klawisza "Szukaj" ekran powinien przesunąć się choć trochę w dół tak, aby widać było choć pierwsze wyniki. Obecnie po naciśnięciu mamy wrażenie, że nic się nie stało / wyszukiwarka ofert nie działa.

**Comment by pureunderground** [comment]
Gotowe

**Comment by bmankowski** [comment]
Super
