### ISSUE TITLE
Wysłanie zgłoszenia - niedozwolony plika załącznika

### ISSUE THREAD

**Issue by bmankowski** [bmankowski/itconnect-www#23]
Strona u mnie (full  hd) wyjeżdża poza ekran (Screenshot w załączniku)
![plik nie dozwolony](https://cloud.githubusercontent.com/assets/9974287/14630006/ebd878c0-060a-11e6-9358-8f72e7f772f8.png)

**Comment by pureunderground** [comment]
Widok poprawiony

**Comment by bmankowski** [comment]
Działa
