### ISSUE TITLE
Gdy jesteśmy na ofercie pracy i zmieniamy język, to pojawia się komunikat

### ISSUE THREAD

**Issue by bmankowski** [bmankowski/itconnect-www#28]
"Niestety, nie mogliśmy znaleźć strony, której szukasz ... " lub "Sorry, we could not find the page you were looking for ... " w zależności od wybranego języka

**Comment by pureunderground** [comment]
Komunikat pojawił się ponieważ nie było przygotowanego tłumaczenia dla danej oferty pracy. System wielojęzyczności w systemie Joomla stworzony jest w taki sposób że pozwiązujemy ze sobą artykuły w języku polskim i angielskim, poniżej krótka instrukcja jak to zrobić na przykładzie ofert pracy.
1) Tworzymy nową ofertę pracy w języku polskim (kategoria "Praca"), po prawej stronie ustawiamy język na "Polish (PL)" i naciskamy na "Zapisz i zamknij".
2) Tworzymy tłumaczenie oferty pracy w języku angielskim (kategoria "Jobs"), po prawej stronie ustawiamy język na "English (UK)" i robimy powiązanie  artykułu z jego odpowiednikiem w języku polskim:
- w zakładce "Skojarzone" naciskamy na "Wybierz i wybieramy z listy uprzednio stworzony artykuł języku polskim, następnie naciskamy na "Zapisz i zamknij".

Artykuły od teraz są ze sobą powiązane, działa przełączanie tłumaczeń. 

Kiedy artykuły są już ze sobą powiązane, w zakładce "Powiązane" możemy bezpośrednio poprawiać  tłumaczenia bez potrzeby szukania artykułów w kategoriach.

**Comment by bmankowski** [comment]
ok
