### ISSUE TITLE
Błędny format dat przy ofertach pracy.

### ISSUE THREAD

**Issue by bmankowski** [bmankowski/itconnect-www#3]
Jak są daty przy ofertach pracy, to jest jakiś totalnie dziwny format: MM.DD.RRRR, a powinno być chyba DD.MM.RRRR lub RRRR-MM-DD

**Comment by pureunderground** [comment]
Gotowe:
http://www.pureunderground-studio.pl/DEMO/itconnect/pl/praca/postings

**Comment by bmankowski** [comment]
Brak ofert pracy do weryfikacji.

**Comment by pureunderground** [comment]
Poprawione

**Comment by bmankowski** [comment]
Poprawione.
