### ISSUE TITLE
Gdzie można dodać dodatkowe miasta/Profile?

### ISSUE THREAD

**Issue by bmankowski** [bmankowski/itconnect-www#30]

**Comment by pureunderground** [comment]
Dodatkowe pola dodajemy w menu Komponenty->Fields Attach->W lewej kolumnie klikamy na "Fields". Otworzy się nam okno w którym wybieramy interesującą nas grupę, dalej klikamy na zakładkę "More Options" i dodatkowe pola dodajemy guzikiem "Add". Proszę pamiętać żeby ustawiać numer ID dla pól, czyli 101, 102, 103 itd. Po dodaniu nowych pól klikamy na "Zapisz i zamknij"

**Comment by bmankowski** [comment]
nieakualne
