### ISSUE TITLE
Strona główna - Oferta dla Klientów / Oferta dla poszukujących pracy

### ISSUE THREAD

**Issue by bmankowski** [bmankowski/itconnect-www#31]
Cały czas button "Oferta dla Klientów" jest pomarańczowy, a button " Oferta dla poszukujących pracy" zmienia się od tego czy jest na nim mysz.
Czy możemy zrobić aby ujednolicić to zachowanie i "Oferta dla Klientów" też była szara i robiła się pomarańczowa dopiero przy focusie?

**Comment by bmankowski** [comment]
To samo jest "Przy co zyskasz jako pracodawca"

**Comment by pureunderground** [comment]
Poprawione

**Comment by bmankowski** [comment]
OK
