### ISSUE TITLE
Strefa pracownika - szara ramka z logo 

### ISSUE THREAD

**Issue by bmankowski** [bmankowski/itconnect-www#35]

**Comment by bmankowski** [comment]
Czy możemy zmienić tę ramkę na coś ładniejszego, jakieś zdjęcie, czy coś podobnego? Tak jak jest w innych częściach portalu.

**Comment by pureunderground** [comment]
Gotowe

**Comment by bmankowski** [comment]
Teraz wygląda to o wiele lepiej :)
