### ISSUE TITLE
Dla szukających pracy - uzupełnienie contentu

### ISSUE THREAD

**Issue by bmankowski** [bmankowski/itconnect-www#38]
http://www.pureunderground-studio.pl/DEMO/itconnect/pl/dla-szukajacych-pracy

**Comment by pureunderground** [comment]
Uzupełnione

**Comment by bmankowski** [comment]
pozytywnych wynikach testu i przejściu do drugiego etapu rekrutacji zostaną PAństwo ponformowani telefonicznie.

Czy mogę prosić o zamianę PAństwo na Państwo

**Comment by pureunderground** [comment]
oczywiście, już poprawione

**Comment by bmankowski** [comment]
Super!
