### ISSUE TITLE
Strona główna - coś się rozjeżdża z layoutem nad danymi adresowymi

### ISSUE THREAD

**Issue by bmankowski** [bmankowski/itconnect-www#39]

**Comment by bmankowski** [comment]
![rozjazd](https://cloud.githubusercontent.com/assets/9974287/14667474/c72d2680-06df-11e6-9915-1232f06b0c50.png)

**Comment by pureunderground** [comment]
Poprawione, proszę nie włączać opcji "Przełącz stan wyróżnienia" na liście artykułów (ikona gwiazdki). Artykuły z ty oznaczeniem będą wyświetlane na stronie głównej nad kontaktem.

**Comment by bmankowski** [comment]
Super
