### ISSUE TITLE
Różne ramki 

### ISSUE THREAD

**Issue by bmankowski** [bmankowski/itconnect-www#4]
Na stronie głównej te na samej górze są kanciaste, a wszystkie pozostałe lekko zaokrąglone. Wydaje mi się, że zdecydowanie bardziej spójnie by było, jakby wszystkie były w takim samym stylu (zaokrąglone wyglądają ładniej;)).

**Comment by pureunderground** [comment]
Tutaj prosiłbym o doprecyzowanie o które ramki dokładnie chodzi ?

**Comment by pureunderground** [comment]
Gotowe

**Comment by bmankowski** [comment]
OK
