### ISSUE TITLE
Ekspert / Konsultant Biznesowy [840] (Alias: ekspert-konsultant-biznesowy-840) 

### ISSUE THREAD

**Issue by bmankowski** [bmankowski/itconnect-www#41]
Ma status "Oczekuje", nie widać go w systemie, jak uniknąć tego problemu?

**Comment by pureunderground** [comment]
Na serwerze byłą ustawiona uniwersalna strefa czasowa, teraz jest ustawiona na prawidłową. Proszę sprawdzić datę publikacji artykułu, jeżeli jest ona przyszła to artykuł będzie oczekiwać na publikację i pojawi się automatycznie. W tym konkretnym przypadku jest to za dwie godziny.

**Comment by bmankowski** [comment]
OK
