### ISSUE TITLE
Jak zrobić punktowanie w ogłoszeniach?

### ISSUE THREAD

**Issue by bmankowski** [bmankowski/itconnect-www#44]
Ogłoszenia dodają się poprawnie, tzn. po opcji zapisania ogłoszenia, pojawia się ono na stronie.
Natomiast aby ogłoszenie wyglądało tak aby tekst pod kolejnymi nagłówkami był równy, trzeba tekst wykropkować, tylko wtedy jest ok. Po drugie punktowanie nie jest widoczne, ani kiedy korzysta się z opcji w panelu, ani kiedy przekleja się wypunktowanie z notatnika, zostaje sam tekst. To pewnie szczegół, ale w ogłoszeniu dobrze by było, żeby punktowanie było możliwe.

**Comment by pureunderground** [comment]
Punktowanie włączone

**Comment by bmankowski** [comment]
Działa
