### ISSUE TITLE
Nie działa sortowanie dla opcji "Nie opublikowane"

### ISSUE THREAD

**Issue by bmankowski** [bmankowski/itconnect-www#45]
Nie działa opcja sortowania ogłoszeń kiedy wybieram opcję "Nie opublikowane". Są takie na liście, ale po wybraniu tej opcji, pokazuje: "nie znaleziono". Sortowanie z wyborem opcji "Opublikowane" działa poprawnie. Sortowanie według autora w obu opcjach też działa poprawnie.

**Comment by pureunderground** [comment]
Poprawione. Do listy doszła trzecia pozycja (Usunięte). Na liście opublikowanych wyświetlane są ogłoszenia ze specjalnym prawem publikacji (data w przyszłości bądź publikacje wygasłe).

**Comment by bmankowski** [comment]
Nie działa mi ta lista

**Comment by bmankowski** [comment]
Ok, wszystko działa
