### ISSUE TITLE
Nie działa opcja publikacji oferty od wybranego dnia w zakładce Publikacja.

### ISSUE THREAD

**Issue by bmankowski** [bmankowski/itconnect-www#46]
Nie działa opcja publikacji oferty od wybranego dnia w zakładce Publikacja. To znaczy, ogłoszenie przy którym zaznaczamy, że ma być opublikowane np. od 25.06. jest widoczne na stronie ITC już teraz, chociaż na liście ogłoszeń, jest informacja że ogłoszenie jest opublikowane ale oczekuje

**Comment by pureunderground** [comment]
Poprawione

**Comment by bmankowski** [comment]
Powinno działać, sprawdzę, czy jutro działa "Test G"

**Comment by bmankowski** [comment]
Sprawdzę jutro, ponieważ nie działa opcja "Od godziny"

**Comment by bmankowski** [comment]
Na razie jeszcze nie opublikowała się automatycznie.

**Comment by bmankowski** [comment]
Obecnie jest już opublikowana. Zamykam.
