### ISSUE TITLE
Zmiana z Oli Gochnio na: Aleksandra Mazek  amazek@itconnect.pl

### ISSUE THREAD

**Issue by bmankowski** [bmankowski/itconnect-www#5]
Ode mnie prośba o zmianę nazwiska i adresu e-mail:

Aleksandra Mazek

amazek@itconnect.pl

**Comment by pureunderground** [comment]
Gotowe:
http://www.pureunderground-studio.pl/DEMO/itconnect/pl/o-nas

**Comment by bmankowski** [comment]
Zamykam
