### ISSUE TITLE
Bulk

### ISSUE THREAD

**Issue by bmankowski** [bmankowski/itconnect-www#50]
Przepraszam, ale mam dostęp jeszcze tylko przez chwilę do komputera, dlatego wkładam tu całą zawartość maila bez sprawdzenia i podzielenia na tickety:

Jeśli chodzi o nowy link do strony, który przesłałeś jako drugi:
-oferta dodaje się poprawnie, jest widoczna na stronie ITC
-aby treść ogłoszenia po opublikowaniu na stronie była równa, należy treść wypunktować, punktory nie są widoczne po opublikowaniu oferty (a dobrze, żeby była możliwość ich dodania), jeśli nie użyjemy punktowania treść jest poprzesuwana/ nierówna
-nie działa opcja publikowania stworzonej oferty od wybranego dnia, od razu widoczna jest na stronie ITC
-nie działa opcja sortowania na liście ofert na panelu administracyjnym (tym razem też jedynie w przypadku ofert „nieopublikowanych”) – czyli sortowanie po tej kategorii nie wyświetla żadnych ofert, choć takie istnieją na liście.

Proszę potraktować to jako jeden ticket.
Pozdrawiam :)

**Comment by pureunderground** [comment]
Wszystkie pozycje w ticket'cie poprawione.

**Comment by bmankowski** [comment]
Ok
