### ISSUE TITLE
W ofertach po angielsku są polskie obiekty (Lokalizacja) 

### ISSUE THREAD

**Issue by bmankowski** [bmankowski/itconnect-www#52]
Czy te elementy są edytowalne z ogłoszenia?

**Comment by bmankowski** [comment]
Są edytowalne

**Comment by bmankowski** [comment]
Lokalizacja nie jest edytowalna, proszę o przetłumaczenie na stronie w wersji angielskiej.

**Comment by bmankowski** [comment]
chodzi mi po prostu o to, aby na stronie ogłoszenia wyświetlało się "Location" zamiast "Lokalizacja" - Warszawa / Łódź czy inna wartość może zostać.

**Comment by pureunderground** [comment]
Poprawione

**Comment by bmankowski** [comment]
ok
