### ISSUE TITLE
Nie działa dodawanie ofet - niestety nie pojawia się jaki błąd - jest tylko różowe pole

### ISSUE THREAD

**Issue by bmankowski** [bmankowski/itconnect-www#53]
![brak bledu](https://cloud.githubusercontent.com/assets/9974287/16378493/7a7c0fe6-3c6c-11e6-89c5-c734249df3b8.png)

**Comment by bmankowski** [comment]
Brak komunikatu pojawia się, gdy nie ma wybranego miasta / Stanowiska - Czy może Pan go dodać?

**Comment by pureunderground** [comment]
Poprawione
