### ISSUE TITLE
Problem z dodawaniem niewypunktowanego ogłoszenia

### ISSUE THREAD

**Issue by bmankowski** [bmankowski/itconnect-www#56]
W przypadku tekstu niewypunktowanego, tenże rozjeżdża się:
http://www.pureunderground-studio.pl/DEMO/itconnect3/pl/praca/325-programista-java-praca-zdalna-900-o

**Comment by pureunderground** [comment]
Problem natury ustawienia odpowiedniego formatowania przez wprowadzającego oferty. W danym przykładzie należy przed tekstem który jest "rozjechany" (a w istocie to zwykły tekst z mniejszą) ustawić kursor, następnie włączyć wypunktowanie -  tekst przeskoczy do nowej linii z wypunktowaniem.

**Comment by bmankowski** [comment]
Jasne, ale tu chodzi o możliwość wprowadzenia akapitu z tekstem niewypunktowanym - wtedy nie działa dołożenie entera - całość wyświetla się w jednej linijce.

**Comment by pureunderground** [comment]
Poprawione, wystarczy nacisnąć enter, nie trzeba włączać wypunktowania
http://www.pureunderground-studio.pl/DEMO/itconnect3/pl/praca/325-programista-java-praca-zdalna-900-o

**Comment by bmankowski** [comment]
ok
