### ISSUE TITLE
Miasta/ Lokalizacji w treści ogłoszenia - przesunięte zbyt mocno w prawo.

### ISSUE THREAD

**Issue by bmankowski** [bmankowski/itconnect-www#58]
Miasta/ Lokalizacji w treści ogłoszenia - przesunięte zbyt mocno w prawo, w stosunku do reszty treści ogłoszenia. O ile przy wypunktowanej treści aż tak bardzo tego nie widać, to przy braku punktorów w treści, jest to widoczne.

**Comment by pureunderground** [comment]
Poprawione

**Comment by bmankowski** [comment]
ok
