### ISSUE TITLE
CV obowiązkową pozycją 

### ISSUE THREAD

**Issue by bmankowski** [bmankowski/itconnect-www#59]
Dodanie pliku CV w przesłanej kandydaturze powinno było obowiązkowe dla wysłania aplikacji o stanowisko, tak jak obowiązkowe jest zaznaczenie klauzuli - obecnie zdarzają się aplikacje bez załącznika.

**Comment by pureunderground** [comment]
Gotowe

**Comment by bmankowski** [comment]
ok
