### ISSUE TITLE
Wygląd oferty pracy 

### ISSUE THREAD

**Issue by bmankowski** [bmankowski/itconnect-www#6]
Chodzi o wygląd  oferty pracy po jej wybraniu z listy – trochę nie po kolei są ustawione części ogłoszenia. Zaczęłabym od zakresu obowiązków, potem wymagania, dodatkowe atuty, oferujemy i lokalizacja.

To drobiazg, ale trochę nie pasują mi niektóre symbole przypisane do tych części, np. koło zębate do zakresu obowiązków – bardziej kojarzy mi się to z rzeczami technicznymi czyli może z wymaganiami niż zadaniami, obowiązkami. Gwiazdka do atutów mi pasuje, tak jak znaczek przy lokalizacji – fajnie dopasowany. Agnieszka zwróciła uwagę, że te symbole są troszkę za duże, może spróbować zmniejszyć?

**Comment by pureunderground** [comment]
Poprawioną wersję prześlę Panu jutro wieczorem (tj. 5.11)

**Comment by bmankowski** [comment]
W systemie nie ma ofert pracy, nie mogę zweryfikować poprawności.

**Comment by pureunderground** [comment]
Poprawione

**Comment by bmankowski** [comment]
Poprawione.
