### ISSUE TITLE
Problem z kalendarzem - przesunięte dni tygodnia

### ISSUE THREAD

**Issue by bmankowski** [bmankowski/itconnect-www#61]
Gdy kandydat aplikuje na ofertę pracy i uzupełnia formularz, to w okienku „Dostępny od” pojawia się kalendarz, gdzie można zaznaczyć datę. Niestety kalendarz jest poprzesuwany - dni tygodnia - prawdopodobnie etykiety dni -  (np. według tego kalendarza jest dzisiaj 05/07/2016 środa a nie wtorek zgodnie z rzeczywistością)

**Comment by pureunderground** [comment]
Poprawione

**Comment by bmankowski** [comment]
Czy kalendarz może zaczynać się od poniedziałku?

**Comment by pureunderground** [comment]
niestety komponent zaprojektowany jest tak że nie ma możliwości zmiany kolejności dni tygodnia

**Comment by bmankowski** [comment]
ok
