### ISSUE TITLE
Brak błędu z załączeniem CV w nieprawidłowym formacie

### ISSUE THREAD

**Issue by bmankowski** [bmankowski/itconnect-www#62]
Nic się nie pokazuje, gdy CV jest w formacie np.txt - brak informacji, czemu nie można aplikować przez stronę

**Comment by pureunderground** [comment]
Poprawione, wyświetla się już komunikat. Proszę o listę dozwolonych formatów.

**Comment by bmankowski** [comment]
To będzie:
ANS,ASC,CSV,doc,docx,pdf,txt,docm,gdoc,ODM,ODT,PDF,MCW,RTF,WPS,HTM,HTML,XML,WRI,XPS

**Comment by pureunderground** [comment]
gotowe

**Comment by bmankowski** [comment]
Działa.
