### ISSUE TITLE
Mail - nowe zgłoszenie - dochodzi na adres Kandydata, a nie na rekrutacji

### ISSUE THREAD

**Issue by bmankowski** [bmankowski/itconnect-www#64]

**Comment by pureunderground** [comment]
Powiadomienia o nowych kandydatach są wysyłane na adres: rekrutacja@itconnect.pl - temat "Nowe zgłoszenie"

Dodarkowo, kandydat na swój adres dostaje potwierdzenie maila z tematem: Potwierdzenie złożenia aplikacji w itconnect.pl

**Comment by bmankowski** [comment]
Kandydat w dalszym ciągu otrzymuje dwa maile: potwierdzenie złożenie oferty i nowe zgłoszenie- to drugie powinno przychodzić tylko na rekrutację, a przychodzi na rekrutację i do kandydata .

**Comment by pureunderground** [comment]
Poprawione

**Comment by bmankowski** [comment]
Teraz działa to tak, że mail idzie tylko do kandydata z podziękowaniem, za wzięcie udziału  w rekrutacji, a nic nie dochodzi do nas

**Comment by pureunderground** [comment]
Proszę sprawdzić teraz, wszystko powinno być okej

**Comment by bmankowski** [comment]
OK, działa, mamy tylko jeszcze jedną prośbę, czy może Pan zmienić nadawcę maila, który idzie na adres rekrutacyjny z powiadomieniem o nowym kandydacie, na adres "aplikuj@itconnect.pl".
Czyli chcielibyśmy, aby maile do Kandydatów nadal szły z rekrutacja@itconnect.pl

**Comment by pureunderground** [comment]
Gotowe, proszę sprawdzić czy wszystko działa.

**Comment by bmankowski** [comment]
ok
