### ISSUE TITLE
Czy możemy usunąć przycisk „Wyloguj” w artykułach (podstronach) strefy pracownika?

### ISSUE THREAD

**Issue by bmankowski** [bmankowski/itconnect-www#65]
Pojawia się na samej górze każdej z podstron, czy możemy go usunąć z podstron strefy pracownika?

**Comment by bmankowski** [comment]
![rozjazd w strefie pracownika](https://cloud.githubusercontent.com/assets/9974287/16685478/a1389e90-450b-11e6-93ab-7875439c7dca.png)

**Comment by pureunderground** [comment]
System jest zaprojektowany w ten sposób że guzik wyloguj musi być wyświetlany na wszystkich podstronach widocznych tylko dla zarejestrowanych osób.

**Comment by bmankowski** [comment]
A czy może Pan go przesunąć na spód strony, za wszystkimi zajawkami artykułów?

**Comment by pureunderground** [comment]
Gotowe

**Comment by bmankowski** [comment]
ok
