### ISSUE TITLE
Rozjazd layoutu w strefie pracownika

### ISSUE THREAD

**Issue by bmankowski** [bmankowski/itconnect-www#66]
![rozjazd w strefie pracownika](https://cloud.githubusercontent.com/assets/9974287/16685491/b948bb32-450b-11e6-9c31-df61b906fccd.png)

**Comment by pureunderground** [comment]
Problemem jest artykuł "Szkolenia" który zawiera przyklejony kod powodujący rozjazd layoutu. Usunąłem publikację artykułu, proszę napisać (nie przeklejać go z kodem) jeszcze raz.

**Comment by bmankowski** [comment]
ok
