### ISSUE TITLE
Mała ikonka jest rozmazana

### ISSUE THREAD

**Issue by bmankowski** [bmankowski/itconnect-www#7]
Ikonka wykorzystywana np. w zakładkach w Firefox jest rozmazana. Proszę o wykorzystanie tej ze starego portalu

**Comment by pureunderground** [comment]
Poprawione

**Comment by bmankowski** [comment]
Nadal jest rozmazana. Załączam printscreena otwartych zakładek z nową i starą stroną.
![male_loga](https://cloud.githubusercontent.com/assets/9974287/11503474/1b8f6aac-9841-11e5-8973-58e534456eb2.png)

**Comment by bmankowski** [comment]
Poprawione
