### ISSUE TITLE
Dodanie informacji pod ogłoszeniami o pracę.

### ISSUE THREAD

**Issue by bmankowski** [bmankowski/itconnect-www#71]
Proszę o dodanie takiej informacji pod listą ofert o pracę:
"Jeśli nie znalazłeś interesującej Cię oferty, możesz wysłać CV bezpośrednio na naszego maila rekrutacyjnego: rekrutacja@itconnect.pl"

**Comment by pureunderground** [comment]
Gotowe

**Comment by bmankowski** [comment]
ok
