### ISSUE TITLE
Główne logo IT Connect jest rozmazane

### ISSUE THREAD

**Issue by bmankowski** [bmankowski/itconnect-www#8]

**Comment by pureunderground** [comment]
Prosiłbym o informację czy posiadają Państwo logotyp w wersji wektorowej ? Moglibyśmy wtedy umieścić na stronie logo w formacie .svg (format bezstratny jeśli chodzi o jakość przy skalowaniu)

**Comment by bmankowski** [comment]
Przesłałem na maila.

**Comment by pureunderground** [comment]
Poprawione

**Comment by bmankowski** [comment]
Poprawione
