### ISSUE TITLE
Layout Ofert Pracy rozjeżdża się na telefonach

### ISSUE THREAD

**Issue by bmankowski** [bmankowski/itconnect-www#9]
Wyszukiwarka przesłania oferty

**Comment by pureunderground** [comment]
Poprawioną wersję prześlę Panu jutro wieczorem (tj. 5.11)

**Comment by bmankowski** [comment]
Layout nadal jest nie poprawny (Samsung Galaxy Note 4, przeglądarka domyślna - Internet)

**Comment by pureunderground** [comment]
Proszę sprawdzić najnowszą wersję strony, wszystko powinno być już okej.

**Comment by bmankowski** [comment]
Poprawione.
